=== MORTAL8900912384/FSD-KNOCKOUT-MMA/knockout_mma.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="knockout_mma">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fighter" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="weight_class">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Lightweight"/>
                                        <xs:enumeration value="Bantamweight"/>
                                        <xs:enumeration value="Featherweight"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                           <xs:element name="wins">
    <xs:simpleType>
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="30"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MORTAL8900912384/FSD-KNOCKOUT-MMA/knockout_mma.xml
<?xml version="1.0" encoding="UTF-8"?>


<knockout_mma xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="knockout_mma.xsd">
    <fighter>
        <name>Conor McGregor</name>
        <weight_class>Lightweight</weight_class>
        <wins>22</wins>
    </fighter>
    <fighter>
        <name>Amanda Nunes</name>
        <weight_class>Bantamweight</weight_class>
        <wins>23</wins>
    </fighter>
</knockout_mma>
